name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd RealWorld/
          git pull
          bundle install
          RAILS_ENV=production bundle exec rake db:migrate
          RAILS_ENV=production bundle exec rake assets:precompile
          sudo systemctl restart nginx
